[project]
name = "cch_his_auto_lib"
version = "0.1.0"
description = "Library for automating your HIS workflow at CCH"
readme = "README.md"
authors = [{ name = "vuongkienthanh", email = "thanhstardust@outlook.com" }]
requires-python = ">=3.13"
dependencies = ["rich>=14.1.0", "selenium>=4.29.0"]

[dependency-groups]
dev = ["pdoc>=15.0.1"]
